### ISSUE TITLE
[Bug 🐛]: Invalid URL when signing up

### ISSUE THREAD

**Issue by MaverickDe** [brave-chat/brave-chat#45]
👶 Getting Started
Please [search the history](https://github.com/brave-chat/brave-chat/issues) to see if an issue already exists for the same problem.

 I have searched the existing issues.
 I have tested the latest version.

📝 Describe the feature
When trying to sign up, The URL generated contains an "undefined" parameter which makes it to return a 404

📸 Screenshots
![IMG_20221112_221043_258](https://user-images.githubusercontent.com/100746581/201495195-85c4a9fa-3454-4cb0-8096-caebcc072f6e.jpg)

🔦 Context
That's it. Good luck!

**Comment by wiseaidev** [comment]
Hey @MaverickDe. Thanks for raising that. That's because you have to set the following env vars:

```sh
export REACT_APP_SERVER_URL=http://localhost:8000/api/v1
export REACT_APP_SOCKET_URL=ws://localhost:8000/api/v1/ws
```

But, since you only want to work on the client, you can call the EditInfo component in place of [`SignIn`](https://github.com/brave-chat/brave-chat/blob/main/src/pages/Login/index.js) or other components that don't require auth, like the following:

```sh
import React from "react";
import EditPersonalInformation from "../../components/EditInfo";

const Login = () => <EditPersonalInformation open={true} />;

export default Login;
```
